[project]
name = "langchain-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-google-vertexai>=3.1.1",
    "langchain[anthropic,google-genai]>=1.1.2",
    "python-dotenv>=1.2.1",
]
